from . import farmers_survey
from . import tree_survey
from . import cook_stove_survey
from . import water_wells_survey
from . import district_village
from . import products_batch_split
from . import stock_move
from . import stock_picking_type
from . import configuration
from . import res_partner_inherit
from . import res_users_inherit
from . import product_prices
